# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('post_img', models.ImageField(upload_to='media/%Y/%m/%d/')),
            ],
        ),
    ]
