# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20171031_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
