# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='post_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='ashjasd', upload_to='media/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
