# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20171101_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_img',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='ASDQWEQW', upload_to='%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='ashasghgashgjasd', editable=False),
            preserve_default=False,
        ),
    ]
