# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('p', 'Published'), ('u', 'Unpublished'), ('a', 'Archived')], default='u', max_length=1),
        ),
    ]
