# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_auto_20171128_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
