# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='uploads',
            field=models.IntegerField(default=0),
        ),
    ]
