# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_auto_20171228_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
