# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_scrapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300)),
                ('app_id', models.CharField(max_length=20)),
                ('app_secret_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='FbToken',
        ),
    ]
