# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_scrapper', '0002_auto_20171119_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('media_file_counter', models.CharField(max_length=4)),
            ],
        ),
    ]
