# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_scrapper', '0003_facebookdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookdata',
            name='media_file_counter',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='facebookdata',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
