# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_scrapper', '0004_auto_20171119_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookauth',
            name='token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
