# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_scrapper', '0007_auto_20171207_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('app_id', models.CharField(max_length=50)),
                ('secret_id', models.CharField(max_length=100)),
            ],
        ),
    ]
